### ISSUE TITLE
Import error due to missing CUDA_HOME

### ISSUE THREAD

**Issue by calebthomas259** [IBM/triton-dejavu#2]
Thank you for making this package, it's really awesome! My startup latency has been reduced from minutes to seconds.

Anyway, when I install triton-dejavu and try to import it, I get this error:

```
[triton-dejavu] determining cuda version failed with: unsupported operand type(s) for +: 'NoneType' and 'str'

Can't determine cuda version and also CONTAINER_CUDA_VERSION is not set
```

I believe the function [`_get_cuda_version()`](https://github.com/IBM/triton-dejavu/blob/2dfcd39bafdcde65d6bff2753d64f12414f497b4/triton_dejavu/dejavu_utilities.py#L41) throws an error because I installed pytorch/triton directly into a miniconda environment instead of using the pytorch Docker container, and as far as I can tell, the direct installation does not set CUDA_HOME or install nvcc... For now, I can work around it by running python with the environment variable `CONTAINER_CUDA_VERSION` set to the correct value (in my case "12.1") but this seems a bit hacky.

The [pytorch documentation](https://pytorch.org/docs/stable/notes/hip.html#checking-for-hip) mentions `torch.version.cuda` (this gives "12.1" on my system) which could presumably be used as a replacement for checking nvcc? Although I'm not sure of the exact semantics of this value, so it would be good to investigate before changing anything. Another advantage of this approach is that we could check `torch.version.hip` too, which would hopefully make things work with AMD GPUs as well.

Cheers!

**Comment by bringlein** [comment]
Thanks for your feedback @calebthomas259, it is much appreciated! 

Yes, the determination of the cuda version is currently a "bit hacky". I'm aware of `toch.version` etc. and that is used *also* by triton-dejavu. However, this returns just the cuda version that pytorch is using (which is shipped with pytorch as binaries). And this is not always the same like the CUDA version of the installed driver, which is then used at runtime. And the "cuda driver" is used by triton to generate the cuda binary from PTX. 
So, the cuda version of `_get_cuda_version` is the runtime version, which is needed because my research showed that different cuda/driver versions translate the triton IR differently and that results in different kernel behaviour (e.g. switching from 12.1 to 12.4). 

Nevertheless, your post made me thinking how triton itself figures out which [ptxas version is installed](https://github.com/triton-lang/triton/blob/9d6736a501d0499348d48d192b6260338ca19da0/third_party/nvidia/backend/compiler.py#L41-L44). So maybe I try to re-use this function for triton-dejavu....I will try this out in the coming days.

**Comment by bringlein** [comment]
I had some time today and I implemented and tested a different cuda runtime version discovery, based on how triton is doing it as well (as discussed). I also added the corresponding rocm version. 

I hope this solves your issue @calebthomas259 ! Maybe you could try the latest version...thanks!

**Comment by calebthomas259** [comment]
Based on my preliminary testing it now works perfectly! I'll let you know if I end up having any related issues later on.

Thanks heaps!
